#ifndef BOSONOGAIMPLEMENTATION_BOSONOGAPRIMITIVES_H
#define BOSONOGAIMPLEMENTATION_BOSONOGAPRIMITIVES_H

#ifndef BOSONOGA_EMPTY_STRING
#define BOSONOGA_EMPTY_STRING ""
#endif //BOSONOGA_EMPTY_STRING

#ifndef BOSONOGA_ZERO
#define BOSONOGA_ZERO 0
#endif //BOSONOGA_ZERO

#ifndef BOSONOGA_ONE
#define BOSONOGA_ONE 1
#endif //BOSONOGA_ONE

#ifndef BOSONOGA_START_STRING
#define BOSONOGA_START_STRING "<START>"
#endif //BOSONOGA_START_STRING

#ifndef BOSONOGA_END_STRING
#define BOSONOGA_END_STRING "<END>"
#endif //BOSONOGA_END_STRING

#ifndef BOSONOGA_IMPLEMENTATION_URI_STRING
#define BOSONOGA_IMPLEMENTATION_URI_STRING "bosonogaimplementation"
#endif //BOSONOGA_IMPLEMENTATION_URI_STRING

#ifndef BOSONOGA_MAIN_FILE_STRING
#define BOSONOGA_MAIN_FILE_STRING "main.bosonoga"
#endif //BOSONOGA_MAIN_FILE_STRING

typedef std::int32_t bosonoga_int;
typedef std::string bosonoga_string;

#endif //BOSONOGAIMPLEMENTATION_BOSONOGAPRIMITIVES_H
