apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-permissions-
spec:
  entrypoint: main
  templates:
  - name: main
    container:
      image: alpine:latest
      command: [echo]
      args: ["RBAC permissions are working!"]