#ifndef CSDLRAIN_PLATFORM_H
#define CSDLRAIN_PLATFORM_H

#undef BX_PLATFORM_ANDROID
#undef BX_PLATFORM_BSD
#undef BX_PLATFORM_EMSCRIPTEN
#undef BX_PLATFORM_HAIKU
#undef BX_PLATFORM_HURD
#undef BX_PLATFORM_IOS
#undef BX_PLATFORM_LINUX
#undef BX_PLATFORM_NX
#undef BX_PLATFORM_OSX
#undef BX_PLATFORM_PS4
#undef BX_PLATFORM_PS5
#undef BX_PLATFORM_RPI
#undef BX_PLATFORM_WINDOWS
#undef BX_PLATFORM_WINRT
#undef BX_PLATFORM_XBOXONE

#define BX_PLATFORM_ANDROID    0
#define BX_PLATFORM_BSD        0
#define BX_PLATFORM_EMSCRIPTEN 0
#define BX_PLATFORM_HAIKU      0
#define BX_PLATFORM_HURD       0
#define BX_PLATFORM_IOS        0
#define BX_PLATFORM_LINUX      0
#define BX_PLATFORM_NX         0
#define BX_PLATFORM_OSX        0
#define BX_PLATFORM_PS4        0
#define BX_PLATFORM_PS5        0
#define BX_PLATFORM_RPI        0
#define BX_PLATFORM_WINDOWS    1
#define BX_PLATFORM_WINRT      0
#define BX_PLATFORM_XBOXONE    0

#endif //CSDLRAIN_PLATFORM_H
